<?php
$this->headTitle('New Post');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Add Post'=>$this->url('posts', ['action'=>'add'])
            ]);

$form = $this->form;
$form->get('title')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Enter post title here'
    ]);
$form->get('content')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Type content here',
    'rows'=>12
    ]);
$form->get('tags')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'comma, separated, list, of, tags'
    ]);
$form->get('status')->setAttributes([
    'class'=>'form-control'   
    ]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h3>Tag list for menu sections</h3>
<table class="table table-striped ">
    <tr>
        <th>Projects</th>
        <th>People</th>
        <th>Additional actions</th>
        <th>Lab</th>
        <th>Initiatives</th>
    </tr>
    <tr>
        <td>projects</td>
        <td>peoples</td>
        <td>addactions</td>
        <td>lab</td>
        <td>initiatives</td>
    </tr>
</table>

<div class="row">
    <div class="col-md-12">
        <?= $this->form()->openTag($form); ?>
        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formLabel($form->get('title')); ?>
                <?= $this->formElement($form->get('title')); ?>
                <?= $this->formElementErrors($form->get('title')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('tags')); ?>
                <?= $this->formElement($form->get('tags')); ?>
                <?= $this->formElementErrors($form->get('tags')); ?>
                <p class="help-block">Separate tags with comma.</p>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <?= $this->formLabel($form->get('content')); ?>
                <?= $this->formElement($form->get('content')); ?>
                <?= $this->formElementErrors($form->get('content')); ?>
            </div>
            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>

        

    </div>    
</div>   