<?php
$this->headTitle('About');

$this->mainMenu()->setActiveItemId('about');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Additional actions'=>$this->url('addactions'),
]);
$publicDir = $this->basePath();

if($data){
    foreach($data as $post){ ?>
        <!--        Post content-->
        <div class="h3"><?php echo $post->getTitle()?></div>
        <div class="content"><?php echo $post->getContent(); ?></div>
        <!--        Post content-->

        <!--        Images-->
        <?php foreach ($post->getImages() as $image) {?>
            <img src="<?php echo $publicDir.'/img'.$this->url().'/'.$post->getId().'/'.$image ;?>" alt="asdqwe123">
        <?php } ?>
        <!--        Images-->
        <?php
    }
}
?>



