<?php
$this->headTitle('Initiatives');

$this->mainMenu()->setActiveItemId('initiatives');


$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Initiatives'=>$this->url('initiatives'),
]);
$publicDir = $this->basePath();

if($data){
    foreach($data as $post){ ?>
        <!--        Post content-->
        <div class="h3"><?php echo $post->getTitle()?></div>
        <div class="content"><?php echo $post->getContent(); ?></div>
        <!--        Post content-->

        <!--        Images-->

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="row">
                    <?php foreach ($post->getImages() as $image)  {?>
                        <a href="<?php echo $publicDir.'/img'.$this->url().'/'.$post->getId().'/'.$image ?>" data-toggle="lightbox" data-gallery="gallery" class="col-sm-4">
                            <img src="<?php echo $publicDir.'/img'.$this->url().'/'.$post->getId().'/'.$image ?>" class="img-fluid" >
                        </a>


                    <?php } ?>
                    <!--        Images-->
                </div>
            </div>
        </div>

        <?php
    }
}
?>