<?php

$this->headTitle('Contact Us');

$this->mainMenu()->setActiveItemId('contactUs');

$this->pageBreadcrumbs()->setItems(array(
    'Home'=>$this->url('home'),
    'Contact Us'=>$this->url('contactus')
));

$form = $this->form;
$form->setAttribute('action', $this->url('contactus'));
$form->get('email')->setAttributes(array(
    'class'=>'form-control',
    'placeholder'=>'name@example.com'
));
$form->get('subject')->setAttributes(array(
    'class'=>'form-control',
    'placeholder'=>'Type subject here'
));
//$form->get('phone')->setAttributes(array(
//    'class'=>'form-control',
//    'placeholder'=>'1 (234) 567-8901'
//));
$form->get('body')->setAttributes(array(
    'class'=>'form-control',
    'rows'=>6,
    'placeholder'=>'Type message text here'
));
$form->get('submit')->setAttributes(array('class'=>'btn btn-primary'));
$form->prepare();

?>

<h1>Contact Us</h1>
<p>
    Please fill out the following form to contact us.
    We appreciate your feedback.
</p>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('email')); ?>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('subject')); ?>
            <?php echo $this->formElement($form->get('subject')); ?>
            <?php echo $this->formElementErrors($form->get('subject')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('body')); ?>
            <?php echo $this->formElement($form->get('body')); ?>
            <?php echo $this->formElementErrors($form->get('body')); ?>
        </div>

<!--        <div class="form-group">-->
<!--            --><?php //echo $this->formLabel($form->get('phone')); ?>
<!--            --><?php //echo $this->formElement($form->get('phone')); ?>
<!--            --><?php //echo $this->formElementErrors($form->get('phone')); ?>
<!--        </div>-->

        <div class="form-group">
            <?php echo $this->formLabel($form->get('captcha')); ?>
            <?php echo $this->formElement($form->get('captcha')); ?>
            <?php echo $this->formElementErrors($form->get('captcha')); ?>
            <p class="help-block">Enter the letters above as you see them.</p>
        </div>

        <?php echo $this->formElement($form->get('csrf')); ?>

        <?php echo $this->formElement($form->get('submit')); ?>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2504.477360514468!2d17.032751415981156!3d51.118102346912494!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x470fe8533c67e741%3A0x324762ec6946f2a7!2sFood+Think+Tank+-+Pracownia!5e0!3m2!1spl!2spl!4v1510923731625" width="100%" height="350" class="google-maps" frameborder="0" style="border:0; margin-top:20px;" allowfullscreen></iframe>
